### ISSUE TITLE
bean-price --update has no tests

### ISSUE THREAD

**Issue by blais** [beancount/beanprice#5]
Needs unit testing coverage.
get_price_jobs_up_to_date() is currently untested.

**Comment by doriath** [comment]
Just as FYI: bean-price currently depends on newest code of beancount from v2 branch (I think v3 branch also doesn't work). If `bean-price --update` is run against default v2.3.3, then following error is returned:

```
Traceback (most recent call last):
  File "/home/zurkowski/.local/bin/bean-price", line 10, in <module>                                                                                                                         
    sys.exit(main())                                                                                                                                                                         
  File "/home/zurkowski/.local/lib/python3.7/site-packages/beanprice/price.py", line 821, in main                                                                                            
    args, jobs, entries, dcontext = process_args()                                                                                                                                           
  File "/home/zurkowski/.local/lib/python3.7/site-packages/beanprice/price.py", line 799, in process_args                                                                                    
    args.update_compress))
  File "/home/zurkowski/.local/lib/python3.7/site-packages/beanprice/price.py", line 406, in get_price_jobs_up_to_date                                                                       
    lifetimes.trim_intervals(intervals,
AttributeError: module 'beancount.ops.lifetimes' has no attribute 'trim_intervals'
```

I fixed it with:

```
pip install --upgrade git+https://github.com/beancount/beancount.git@a78dcc2ec2552595a87fcbdb62a4271e1e9b4a58
```

When I have a sec, I can also try taking a stab at writing those unit tests.
