### ISSUE TITLE
Cache causing SQLite error on Python3.13

### ISSUE THREAD

**Issue by iamkroot** [beancount/beanprice#91]
Running `--update` with the latest master branch (https://github.com/beancount/beanprice/commit/e894c9182f4d16f9a46ccb87bdaeca1a7dede040) on Python 3.13 is giving this error-

```python
Traceback (most recent call last):
  File "/usr/lib/python3.13/shelve.py", line 111, in __getitem__
    value = self.cache[key]
            ~~~~~~~~~~^^^^^
KeyError: '63fc5e4df4accf902a48b972b8713d01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/dbm/sqlite3.py", line 79, in _execute
    return closing(self._cx.execute(*args, **kwargs))
                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139682033261440 and this is thread id 139681986561728.
```

<details>
<summary>Full traceback</summary>

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<REDACTED>/bin/bean-price", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "<REDACTED>/lib/python3.13/site-packages/beanprice/price.py", line 961, in main
    price_entries = sorted(price_entries, key=lambda e: e.currency)
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<REDACTED>/lib/python3.13/site-packages/beanprice/price.py", line 595, in fetch_price
    srcprice = fetch_cached_price(source, psource.symbol, dprice.date)
  File "<REDACTED>/lib/python3.13/site-packages/beanprice/price.py", line 509, in fetch_cached_price
    timestamp_created, result_naive = _CACHE[key]
                                      ~~~~~~^^^^^
  File "/usr/lib/python3.13/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/dbm/sqlite3.py", line 89, in __getitem__
    with self._execute(LOOKUP_KEY, (key,)) as cu:
         ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/dbm/sqlite3.py", line 81, in _execute
    raise error(str(exc))
dbm.sqlite3.error: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139682033261440 and this is thread id 139681986561728.
```

</details>

This is likely caused by `sqlite3` [becoming](https://docs.python.org/3/whatsnew/3.13.html#new-modules) the default backend for `dbm` in Python 3.13. [`dbm`](https://docs.python.org/3/library/dbm.html) is internally used by `shelve` module (used for `_CACHE`)

Happens even at default mode of `--workers=1`; not exactly sure where multiple threads are coming into the picture in this case - I would assume the same thread would be doing everything.

Running with `--no-cache` fixes the error, but is obviously not desired.

**Comment by alensiljak** [comment]
Is there a workaround for this? Using `--no-cache` is ok for CLI use but I've created a custom price source and this is happening only when it is used. I see cache is used successfully by the default modules and `pricehist` package.

**Comment by blais** [comment]
Someone make a patch that restores old dbm usage?

**Comment by alensiljak** [comment]
Just tried with Python 3.12 but that throws
```
dbm.error: db type could not be determined
```
<details>
```
Traceback (most recent call last):
  File "/home/alen/.local/bin/bean-price", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/alen/.local/share/uv/tools/beanprice/lib/python3.12/site-packages/beanprice/price.py", line 948, in main
    args, jobs, entries, dcontext = process_args()
                                    ^^^^^^^^^^^^^^
  File "/home/alen/.local/share/uv/tools/beanprice/lib/python3.12/site-packages/beanprice/price.py", line 870, in process_args
    setup_cache(args.cache_filename, args.clear_cache)
  File "/home/alen/.local/share/uv/tools/beanprice/lib/python3.12/site-packages/beanprice/price.py", line 568, in setup_cache
    _CACHE = shelve.open(cache_filename, flag=flag)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alen/.local/share/uv/python/cpython-3.12.10-linux-x86_64-gnu/lib/python3.12/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alen/.local/share/uv/python/cpython-3.12.10-linux-x86_64-gnu/lib/python3.12/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alen/.local/share/uv/python/cpython-3.12.10-linux-x86_64-gnu/lib/python3.12/dbm/__init__.py", line 89, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
```
</details>

**Comment by alensiljak** [comment]
hm, and with 3.11
<details>
<pre>
Traceback (most recent call last):
  File "/home/alen/.local/bin/bean-price", line 4, in <module>
    from beanprice.price import main
  File "/home/alen/.local/share/uv/tools/beanprice/lib/python3.13/site-packages/beanprice/price.py", line 22, in <module>
    from beancount.core.number import ONE
  File "/home/alen/.local/share/uv/tools/beanprice/lib/python3.13/site-packages/beancount/__init__.py", line 23, in <module>
    from .api import *  # noqa: E402, F403
    ^^^^^^^^^^^^^^^^^^
  File "/home/alen/.local/share/uv/tools/beanprice/lib/python3.13/site-packages/beancount/api.py", line 77, in <module>
    from .loader import load_doc
  File "/home/alen/.local/share/uv/tools/beanprice/lib/python3.13/site-packages/beancount/loader.py", line 34, in <module>
    from beancount.parser import parser
  File "/home/alen/.local/share/uv/tools/beanprice/lib/python3.13/site-packages/beancount/parser/parser.py", line 127, in <module>
    from beancount.parser import _parser
ImportError: cannot import name '_parser' from 'beancount.parser' (/home/alen/.local/share/uv/tools/beanprice/lib/python3.13/site-packages/beancount/parser/__init__.py)
</pre>
</details>
Weird.

**Comment by alensiljak** [comment]
I've replaced shelve with diskcache in just a couple of lines of code and it works without errors. It has been suggested as a better multi-platform and multi-threaded alternative to shelve. I will submit a PR and we can discuss there?
